# Generated by Django 4.2.3 on 2023-08-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='color',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='line',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
