# Generated by Django 4.2.3 on 2023-08-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_subcategory_inventoryitem_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
